version: "3.7"

services:

  lavalink:
    image: fredboat/lavalink:master
    ports:
      - 2333:2333
    volumes:
      - ./resources/lavalink/application.yml:/opt/Lavalink/application.yml
      - ./resources/lavalink/logs:/opt/Lavalink/logs
    # If it comes to serving a large amount of guilds, increasing the allocated memory is a must.
    # Change -Xmx to your prefered size. E.g: -Xmx2G for 2GB memory allocated.
    entrypoint: java -Xmx1G -jar Lavalink.jar

  bot:
    build: .
    restart: unless-stopped
    volumes:
      - ./data:/bot/data
      - ./logs:/bot/logs
      - "/etc/localtime:/etc/localtime:ro"
