version: "3.7"

services:
    substiify:
        image: substiify
        container_name: substiify
        volumes:
            - ./data:/bot/data
            - ./logs:/bot/logs
            - "/etc/localtime:/etc/localtime:ro"
        restart: unless-stopped
        stdin_open: true # docker run -i
        tty: true        # docker run -t